spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # ?? ?? update / ??? validate ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  profiles:
    active: ${PROFILE}
  application:
    name: timely

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: trace
